// <auto-generated />
namespace PostThisCatWithConsiderableDelay.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open PostThisCatWithConsiderableDelay.Models

[<DbContext(typeof<CatContext.CatContext>)>]
[<Migration("20210917000324_Add Posts to Guild table")>]
type AddPoststoGuildtable() =
    inherit Migration()

    override this.Up(migrationBuilder: MigrationBuilder) =
        migrationBuilder.AlterColumn<UInt64>(
            name = "UserId",
            table = "Posts",
            ``type`` = "INTEGER",
            nullable = true,
            oldClrType = typedefof<UInt64>,
            oldType = "INTEGER",
            oldNullable = false
        )
        |> ignore

        migrationBuilder.AlterColumn<UInt64>(
            name = "UserGuildId",
            table = "Posts",
            ``type`` = "INTEGER",
            nullable = true,
            oldClrType = typedefof<UInt64>,
            oldType = "INTEGER",
            oldNullable = false
        )
        |> ignore

        migrationBuilder.AddColumn<UInt64>(name = "GuildId", table = "Posts", ``type`` = "INTEGER", nullable = true)
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Posts_GuildId", table = "Posts", column = "GuildId")
        |> ignore

        migrationBuilder.AddForeignKey(
            name = "FK_Posts_Guilds_GuildId",
            table = "Posts",
            column = "GuildId",
            principalTable = "Guilds",
            principalColumn = "GuildId",
            onDelete = ReferentialAction.Restrict
        )
        |> ignore


    override this.Down(migrationBuilder: MigrationBuilder) =
        migrationBuilder.DropForeignKey(name = "FK_Posts_Guilds_GuildId", table = "Posts")
        |> ignore

        migrationBuilder.DropIndex(name = "IX_Posts_GuildId", table = "Posts")
        |> ignore

        migrationBuilder.DropColumn(name = "GuildId", table = "Posts")
        |> ignore

        migrationBuilder.AlterColumn<UInt64>(
            name = "UserId",
            table = "Posts",
            ``type`` = "INTEGER",
            nullable = false,
            defaultValue = 0uL,
            oldClrType = typedefof<UInt64>,
            oldType = "INTEGER",
            oldNullable = true
        )
        |> ignore

        migrationBuilder.AlterColumn<UInt64>(
            name = "UserGuildId",
            table = "Posts",
            ``type`` = "INTEGER",
            nullable = false,
            defaultValue = 0uL,
            oldClrType = typedefof<UInt64>,
            oldType = "INTEGER",
            oldNullable = true
        )
        |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "5.0.10")
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Guild",
            (fun b ->

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("CatChannel")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("GuildId") |> ignore

                b.ToTable("Guilds") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->

                b
                    .Property<Guid>("PostId")
                    .IsRequired(true)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<DateTime>("Timestamp")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserGuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("PostId") |> ignore


                b.HasIndex("GuildId") |> ignore


                b.HasIndex("UserId", "UserGuildId") |> ignore

                b.ToTable("Posts") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+User",
            (fun b ->

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Int64>("Points")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("UserId", "GuildId") |> ignore


                b.HasIndex("GuildId") |> ignore

                b.ToTable("Users") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.User+Guild", null)
                    .WithMany("Posts")
                    .HasForeignKey("GuildId")
                |> ignore

                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.User+User", "User")
                    .WithMany("Posts")
                    .HasForeignKey("UserId", "UserGuildId")
                |> ignore)
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+User",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.User+Guild", "Guild")
                    .WithMany("Users")
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                |> ignore)
        )
        |> ignore
