// <auto-generated />
namespace PostThisCatWithConsiderableDelay.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open PostThisCatWithConsiderableDelay.Models

[<DbContext(typeof<CatContext.CatContext>)>]
[<Migration("20210918133207_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder: MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Guilds",
            columns =
                (fun table ->
                    {| GuildId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       CatChannel = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Guilds", (fun x -> (x.GuildId) :> obj))
                    |> ignore)
        )
        |> ignore

        migrationBuilder.CreateTable(
            name = "Users",
            columns = (fun table -> {| UserId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Users", (fun x -> (x.UserId) :> obj))
                    |> ignore)
        )
        |> ignore

        migrationBuilder.CreateTable(
            name = "Points",
            columns =
                (fun table ->
                    {| PointsId = table.Column<Guid>(nullable = false, ``type`` = "TEXT")
                       UserId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       GuildId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       Points = table.Column<Int64>(nullable = false, ``type`` = "INTEGER") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Points", (fun x -> (x.PointsId) :> obj))
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Points_Guilds_GuildId",
                        column = (fun x -> (x.GuildId) :> obj),
                        principalTable = "Guilds",
                        principalColumn = "GuildId",
                        onDelete = ReferentialAction.Cascade
                    )
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Points_Users_UserId",
                        column = (fun x -> (x.UserId) :> obj),
                        principalTable = "Users",
                        principalColumn = "UserId",
                        onDelete = ReferentialAction.Cascade
                    )
                    |> ignore

                    )
        )
        |> ignore

        migrationBuilder.CreateTable(
            name = "Posts",
            columns =
                (fun table ->
                    {| PostId = table.Column<Guid>(nullable = false, ``type`` = "TEXT")
                       Timestamp = table.Column<DateTime>(nullable = false, ``type`` = "TEXT")
                       UserId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       GuildId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       PointsId = table.Column<Guid>(nullable = true, ``type`` = "TEXT") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Posts", (fun x -> (x.PostId) :> obj))
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Posts_Guilds_GuildId",
                        column = (fun x -> (x.GuildId) :> obj),
                        principalTable = "Guilds",
                        principalColumn = "GuildId",
                        onDelete = ReferentialAction.Cascade
                    )
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Posts_Points_PointsId",
                        column = (fun x -> (x.PointsId) :> obj),
                        principalTable = "Points",
                        principalColumn = "PointsId",
                        onDelete = ReferentialAction.Restrict
                    )
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Posts_Users_UserId",
                        column = (fun x -> (x.UserId) :> obj),
                        principalTable = "Users",
                        principalColumn = "UserId",
                        onDelete = ReferentialAction.Cascade
                    )
                    |> ignore

                    )
        )
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Points_GuildId", table = "Points", column = "GuildId")
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Points_UserId", table = "Points", column = "UserId")
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Posts_GuildId", table = "Posts", column = "GuildId")
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Posts_PointsId", table = "Posts", column = "PointsId")
        |> ignore

        migrationBuilder.CreateIndex(name = "IX_Posts_UserId", table = "Posts", column = "UserId")
        |> ignore


    override this.Down(migrationBuilder: MigrationBuilder) =
        migrationBuilder.DropTable(name = "Posts")
        |> ignore

        migrationBuilder.DropTable(name = "Points")
        |> ignore

        migrationBuilder.DropTable(name = "Guilds")
        |> ignore

        migrationBuilder.DropTable(name = "Users")
        |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "5.0.10")
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+Guild",
            (fun b ->

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("CatChannel")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("GuildId") |> ignore

                b.ToTable("Guilds") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+Points",
            (fun b ->

                b
                    .Property<Guid>("PointsId")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Int64>("Points")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("PointsId") |> ignore


                b.HasIndex("GuildId") |> ignore


                b.HasIndex("UserId") |> ignore

                b.ToTable("Points") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+Post",
            (fun b ->

                b
                    .Property<Guid>("PostId")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Nullable<Guid>>("PointsId")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<DateTime>("Timestamp")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("PostId") |> ignore


                b.HasIndex("GuildId") |> ignore


                b.HasIndex("PointsId") |> ignore


                b.HasIndex("UserId") |> ignore

                b.ToTable("Posts") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+User",
            (fun b ->

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("UserId") |> ignore

                b.ToTable("Users") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+Points",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.Models+Guild", "Guild")
                    .WithMany()
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                |> ignore

                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.Models+User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                |> ignore)
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.Models+Post",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.Models+Guild", "Guild")
                    .WithMany()
                    .HasForeignKey("GuildId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                |> ignore

                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.Models+Points", null)
                    .WithMany("Posts")
                    .HasForeignKey("PointsId")
                |> ignore

                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.Models+User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                |> ignore)
        )
        |> ignore
