// <auto-generated />
namespace PostThisCatWithConsiderableDelay.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open PostThisCatWithConsiderableDelay.Models

[<DbContext(typeof<CatContext.CatContext>)>]
[<Migration("20210916153518_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder: MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Users",
            columns =
                (fun table ->
                    {| UserId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       GuildId = table.Column<UInt64>(nullable = false, ``type`` = "INTEGER")
                       Points = table.Column<Int64>(nullable = false, ``type`` = "INTEGER") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Users", (fun x -> (x.UserId, x.GuildId) :> obj))
                    |> ignore)
        )
        |> ignore

        migrationBuilder.CreateTable(
            name = "Posts",
            columns =
                (fun table ->
                    {| PostId = table.Column<Guid>(nullable = false, ``type`` = "TEXT")
                       UserId = table.Column<UInt64>(nullable = true, ``type`` = "INTEGER")
                       UserGuildId = table.Column<UInt64>(nullable = true, ``type`` = "INTEGER")
                       Timestamp = table.Column<DateTime>(nullable = false, ``type`` = "TEXT") |}),
            constraints =
                (fun table ->
                    table.PrimaryKey("PK_Posts", (fun x -> (x.PostId) :> obj))
                    |> ignore

                    table.ForeignKey(
                        name = "FK_Posts_Users_UserId_UserGuildId",
                        columns = (fun x -> (x.UserId, x.UserGuildId) :> obj),
                        principalTable = "Users",
                        principalColumns = [| "UserId"; "GuildId" |],
                        onDelete = ReferentialAction.Restrict
                    )
                    |> ignore

                    )
        )
        |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_Posts_UserId_UserGuildId",
            table = "Posts",
            columns = [| "UserId"; "UserGuildId" |]
        )
        |> ignore


    override this.Down(migrationBuilder: MigrationBuilder) =
        migrationBuilder.DropTable(name = "Posts")
        |> ignore

        migrationBuilder.DropTable(name = "Users")
        |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "5.0.10")
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->

                b
                    .Property<Guid>("PostId")
                    .IsRequired(true)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<DateTime>("Timestamp")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserGuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("PostId") |> ignore


                b.HasIndex("UserId", "UserGuildId") |> ignore

                b.ToTable("Posts") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+User",
            (fun b ->

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Int64>("Points")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("UserId", "GuildId") |> ignore

                b.ToTable("Users") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.User+User", "User")
                    .WithMany("Posts")
                    .HasForeignKey("UserId", "UserGuildId")
                |> ignore)
        )
        |> ignore
