// <auto-generated />
namespace PostThisCatWithConsiderableDelay.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open PostThisCatWithConsiderableDelay.Models

[<DbContext(typeof<CatContext.CatContext>)>]
type CatContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "5.0.10")
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->

                b
                    .Property<Guid>("PostId")
                    .IsRequired(true)
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<DateTime>("Timestamp")
                    .IsRequired(true)
                    .HasColumnType("TEXT")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserGuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Nullable<UInt64>>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("PostId") |> ignore


                b.HasIndex("UserId", "UserGuildId") |> ignore

                b.ToTable("Posts") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+User",
            (fun b ->

                b
                    .Property<UInt64>("UserId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<UInt64>("GuildId")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b
                    .Property<Int64>("Points")
                    .IsRequired(true)
                    .HasColumnType("INTEGER")
                |> ignore

                b.HasKey("UserId", "GuildId") |> ignore

                b.ToTable("Users") |> ignore

                )
        )
        |> ignore

        modelBuilder.Entity(
            "PostThisCatWithConsiderableDelay.Models.User+Post",
            (fun b ->
                b
                    .HasOne("PostThisCatWithConsiderableDelay.Models.User+User", "User")
                    .WithMany("Posts")
                    .HasForeignKey("UserId", "UserGuildId")
                |> ignore)
        )
        |> ignore
